/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import net.Config;
import net.ConnectionUtil;
import net.ServerInfo;

/**
 *
 * @author amind_000
 */
public class DirectConnect extends ComponentPanel {
	/**
	 * 
	 */
	private String address;
	/**
	 * Creates new form DirectConnect
	 */
	public DirectConnect(ApplicationManager frame) {
		super(frame);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	protected
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		checkAddressButton = new javax.swing.JButton();
		statusLabel = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		connectButton = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		playerNumLabel = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		serverNameLabel = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		serverAddressLabel = new javax.swing.JLabel();

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Direct Connect");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		checkAddressButton.setText("Check Address");
		checkAddressButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkAddressButtonActionPerformed(evt);
			}
		});

		statusLabel.setText("Waiting for user input");

		jLabel4.setText("Server Info:");

		jLabel5.setText("Enter Server Address");

		connectButton.setText("Connect To Server");
		connectButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				connectButtonActionPerformed(evt);
			}
		});

		jLabel2.setText("Players: ");

		playerNumLabel.setText("0/0");

		jLabel7.setText("Name:");

		serverNameLabel.setText("");

		jLabel9.setText("Address:");

		serverAddressLabel.setText("");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								layout.createSequentialGroup()
										.addContainerGap(110,
												Short.MAX_VALUE)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel5).addComponent(jLabel4).addComponent(statusLabel)
												.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 178,
														Short.MAX_VALUE)
								.addComponent(jTextField1)
								.addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(checkAddressButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addGap(10, 10, 10)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel9)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(serverAddressLabel))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel7)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(serverNameLabel)).addGroup(
														layout.createSequentialGroup().addComponent(jLabel2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(playerNumLabel)))))
						.addGap(110, 110, 110)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(18, 18, 18)
						.addComponent(jLabel5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(checkAddressButton)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(statusLabel)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel7)
						.addComponent(serverNameLabel))
				.addGap(3, 3, 3)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(playerNumLabel))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel9)
						.addComponent(serverAddressLabel))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(connectButton)
				.addGap(65, 65, 65)));
	}// </editor-fold>

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void checkAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {
		String address=jTextField1.getText();
		checkAddress(address);
	}
	private void updateInfoArea(ServerInfo info){
		address=info.getAddress();
		serverAddressLabel.setText(address);
		serverNameLabel.setText(info.getServerName());
		playerNumLabel.setText(info.getNumClients()+"/"+info.getMaxClients());
	}
	private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {
		String fieldAddress=jTextField1.getText();
		if(fieldAddress.equals(address)){//address has already been checked
			connect(address);
		}else{
			checkAddress(fieldAddress);
			if(address.equals("")){
				System.out.println("invalid address");
			}else{
				connect(address);
			}
		}
	}
	private void connect(String address){
		frame.enterScreen(new ClientConsolePanel(frame,frame.createClient(address)));
	}
	public void checkAddress(String address){
		serverAddressLabel.setText(address);
		statusLabel.setText("Checking...");
		if(ConnectionUtil.testConnection(address, Config.PORT, 1000, 1000)){
			updateInfoArea(ConnectionUtil.getServerInfo(address,Config.PORT,1000,1000));
			statusLabel.setText("Server available");
		}else{
			updateInfoArea(new ServerInfo("","",0,0));
			statusLabel.setText("No server at requested address");
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton checkAddressButton;
	private javax.swing.JButton connectButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel statusLabel;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JLabel playerNumLabel;
	private javax.swing.JLabel serverAddressLabel;
	private javax.swing.JLabel serverNameLabel;
	// End of variables declaration
}
